FROM ubuntu:20.04 AS build-image

ARG TARGETARCH
ENV TARGETARCH "${TARGETARCH}"

RUN echo "arch:$TARGETARCH" > build-base.txt
RUN apt-get -y update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      wget

ENV PANDOC_VERSION 2.13

RUN wget https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/pandoc-$PANDOC_VERSION-1-$TARGETARCH.deb && \
    dpkg -i pandoc-$PANDOC_VERSION-1-$TARGETARCH.deb
